spring.application.name=student-news

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/student_news}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:student}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:student}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.port=8080
